name: theSEOgrind
favicon: null
layout_spectrum: 0.74855
typography_spectrum: 0.83561
title: theSEOgrind
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-53643241-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d6d6d6'
    - '#000000'
    - '#e88503'
    - '#606060'
    - '#492400'
  brandStrength: 0.9375
  lightness: 0.5625
  saturation: 0.8766525629907846
  rhythmicContrast: 0.04986109142191708
purpose: []
